// Every Tamil term getRelationshipLabelTamil (familyUtils.js) can currently
// produce on its own, paired with a romanized spelling — powers
// EditRelationshipDialog's type-in-English-get-Tamil-suggestions autocomplete.
// Purely a convenience list: picking a suggestion just fills the text field,
// it isn't a constraint — typing anything else (a dialect word, a brand new
// term) and saving it directly works exactly the same way.
export const TAMIL_RELATIONSHIP_TERMS = [
  { en: 'Appa', ta: 'அப்பா' },
  { en: 'Amma', ta: 'அம்மா' },
  { en: 'Thatha', ta: 'தாத்தா' },
  { en: 'Paati', ta: 'பாட்டி' },
  { en: 'Kollu Thatha', ta: 'கொள்ளுத்தாத்தா' },
  { en: 'Kollu Paati', ta: 'கொள்ளுப்பாட்டி' },
  { en: 'Magan', ta: 'மகன்' },
  { en: 'Magal', ta: 'மகள்' },
  { en: 'Peran', ta: 'பேரன்' },
  { en: 'Pethi', ta: 'பேத்தி' },
  { en: 'Kollu Peran', ta: 'கொள்ளுப்பேரன்' },
  { en: 'Kollu Pethi', ta: 'கொள்ளுப்பேத்தி' },
  { en: 'Anna', ta: 'அண்ணன்' },
  { en: 'Thambi', ta: 'தம்பி' },
  { en: 'Akka', ta: 'அக்கா' },
  { en: 'Thangai', ta: 'தங்கை' },
  { en: 'Sagodharan', ta: 'சகோதரன்' },
  { en: 'Sagodhari', ta: 'சகோதரி' },
  { en: 'Mama', ta: 'மாமா' },
  { en: 'Athai', ta: 'அத்தை' },
  { en: 'Periyappa', ta: 'பெரியப்பா' },
  { en: 'Periyamma', ta: 'பெரியம்மா' },
  { en: 'Chithappa', ta: 'சித்தப்பா' },
  { en: 'Chithi', ta: 'சித்தி' },
  { en: 'Sinnamma', ta: 'சின்னம்மா' },
  { en: 'Marumagan', ta: 'மருமகன்' },
  { en: 'Marumagal', ta: 'மருமகள்' },
  { en: 'Maapillai', ta: 'மாப்பிள்ளை' },
  { en: 'Manamagan', ta: 'மணமகன்' },
  { en: 'Manamagal', ta: 'மணமகள்' },
  { en: 'Machaan', ta: 'மச்சான்' },
  { en: 'Machinan', ta: 'மச்சினன்' },
  { en: 'Machinichi', ta: 'மச்சினிச்சி' },
  { en: 'Kozhundhi', ta: 'கொழுந்தி' },
  { en: 'Kozhundhan', ta: 'கொழுந்தன்' },
  { en: 'Naathanaar', ta: 'நாத்தனார்' },
  { en: 'Anni', ta: 'அண்ணி' },
  { en: 'Athaan', ta: 'அத்தான்' },
  { en: 'Maamanaar', ta: 'மாமனார்' },
  { en: 'Maamiyaar', ta: 'மாமியார்' },
  { en: 'Orambadi', ta: 'ஓரம்படி' },
  { en: 'Sagalai', ta: 'சகலை' },
  { en: 'Oppandhiyaar', ta: 'ஓப்பந்தியார்' },
  { en: 'Sambandhi', ta: 'சம்பந்தி' },
  { en: 'Kanavar', ta: 'கணவர்' },
  { en: 'Manaivi', ta: 'மனைவி' },
  { en: 'Ondru Vitta Sagodharan', ta: 'ஒன்று விட்ட சகோதரன்' },
  { en: 'Ondru Vitta Sagodhari', ta: 'ஒன்று விட்ட சகோதரி' },
];
